apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/splunk

images:
  - name: 111111111111.dkr.ecr.us-east-1.amazonaws.com/devops-agent-test/splunk-mcp-server
    newName: 222222222222.dkr.ecr.us-east-1.amazonaws.com/devops-agent-test/splunk-mcp-server
    newTag: streamable-http-v10
