apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secrets.yaml
  - deployment.yaml
  - service.yaml
  - service-hec.yaml
  - mcp-server.yaml
  - hec-setup-job.yaml
  - otel-collector.yaml
