apiVersion: v1
kind: Secret
metadata:
  name: splunk-credentials
  namespace: splunk
type: Opaque
stringData:
  SPLUNK_PASSWORD: "PLACEHOLDER_PASSWORD"
  SPLUNK_HEC_TOKEN: "00000000-0000-0000-0000-000000000001"
