apiVersion: v1
kind: ServiceAccount
metadata:
  name: fis-experiment-sa
  namespace: dockercoins
  annotations: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fis-experiment-sa
  namespace: dockercoins
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "list", "watch", "delete", "patch"]
  - apiGroups: [""]
    resources: ["pods/ephemeralcontainers"]
    verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fis-experiment-sa
  namespace: dockercoins
subjects:
  - kind: ServiceAccount
    name: fis-experiment-sa
    namespace: dockercoins
roleRef:
  kind: Role
  name: fis-experiment-sa
  apiGroup: rbac.authorization.k8s.io
